// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsuarioAPI.Data;

#nullable disable

namespace UsuarioAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250619181920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UsuarioAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Rm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rm"));

                    b.Property<string>("ChamadosAbertos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("ChamadosConcluidos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<int>("IdTipoPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<int>("Senha")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("Rm");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Rm = 123090,
                            ChamadosAbertos = "1",
                            ChamadosConcluidos = "2",
                            Email = "Maria@gmail.com",
                            IdTipoPerfil = 3,
                            Nome = "Maria",
                            Senha = 123456,
                            Telefone = "11 988871234"
                        },
                        new
                        {
                            Rm = 201190,
                            ChamadosAbertos = "2",
                            ChamadosConcluidos = "5",
                            Email = "Eduardo@gmail.com",
                            IdTipoPerfil = 1,
                            Nome = "Eduardo",
                            Senha = 567890,
                            Telefone = "11 908879876"
                        },
                        new
                        {
                            Rm = 339090,
                            ChamadosAbertos = "3",
                            ChamadosConcluidos = "2",
                            Email = "Claudia@gmail.com",
                            IdTipoPerfil = 3,
                            Nome = "Claudia",
                            Senha = 456321,
                            Telefone = "11 989971774"
                        },
                        new
                        {
                            Rm = 123980,
                            ChamadosAbertos = "5",
                            ChamadosConcluidos = "1",
                            Email = "João@gmail.com",
                            IdTipoPerfil = 2,
                            Nome = "João",
                            Senha = 180805,
                            Telefone = "11 911876543"
                        },
                        new
                        {
                            Rm = 150570,
                            ChamadosAbertos = "0",
                            ChamadosConcluidos = "3",
                            Email = "Marcela@gmail.com",
                            IdTipoPerfil = 3,
                            Nome = "Marcela",
                            Senha = 30505,
                            Telefone = "11 955478756"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
