// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsuarioAPI.Data;

#nullable disable

namespace UsuarioAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250623022318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UsuarioAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Rm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rm"));

                    b.Property<string>("ChamadosAbertos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("ChamadosConcluidos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<byte[]>("SenhaHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("TipoPerfil")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("Rm");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Rm = 123090,
                            ChamadosAbertos = "1",
                            ChamadosConcluidos = "2",
                            Email = "Maria@gmail.com",
                            Nome = "Maria",
                            Senha = "123456",
                            Telefone = "11 988871234",
                            TipoPerfil = "Funcionario"
                        },
                        new
                        {
                            Rm = 201190,
                            ChamadosAbertos = "2",
                            ChamadosConcluidos = "5",
                            Email = "Eduardo@gmail.com",
                            Nome = "Eduardo",
                            Senha = "567890",
                            Telefone = "11 908879876",
                            TipoPerfil = "GestorGeral"
                        },
                        new
                        {
                            Rm = 339090,
                            ChamadosAbertos = "3",
                            ChamadosConcluidos = "2",
                            Email = "Claudia@gmail.com",
                            Nome = "Claudia",
                            Senha = "456321",
                            Telefone = "11 989971774",
                            TipoPerfil = "Funcionário"
                        },
                        new
                        {
                            Rm = 123980,
                            ChamadosAbertos = "5",
                            ChamadosConcluidos = "1",
                            Email = "João@gmail.com",
                            Nome = "João",
                            Senha = "180805",
                            Telefone = "11 911876543",
                            TipoPerfil = "GestorDepartamento"
                        },
                        new
                        {
                            Rm = 150570,
                            ChamadosAbertos = "0",
                            ChamadosConcluidos = "3",
                            Email = "Marcela@gmail.com",
                            Nome = "Marcela",
                            Senha = "030505",
                            Telefone = "11 955478756",
                            TipoPerfil = "Funcionario"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
